version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server/src:/app/src
      - ./data:/data
    environment:
      - APP_ENVIRONMENT=development
      - APP_DEBUG=true
      - DB_PATH=/data/productname.db
    env_file:
      - .env
